<?php

namespace Leira_Auth\Public\Fields;

/**
 * WordPress referer hidden field.
 *
 * @since 1.0.0
 */
class Referer extends Hidden{

	/**
	 * Constructor.
	 */
	public function __construct() {
		parent::__construct( '_wp_original_http_referer' );
	}

	/**
	 * Referer field value is generated by WordPress.
	 *
	 * @return mixed
	 */
	public function get_value(): mixed {
		return null;
	}

	/**
	 * Value assignment is ignored.
	 *
	 * @param  mixed  $value
	 *
	 * @return self
	 */
	public function set_value( mixed $value ): self {
		return $this;
	}

}
